### ISSUE TITLE
Add support for cmcrameri color maps

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/atmosphere-virtual-lab#4]
The idea is to combine them by first trying to resolve the color table name from cmcrameri, and if not found try the matplotlib one.

Later on, we might also want to add our own color tables (based on what is used in the atmospheric community) as a third set of name->table mappings (which is then to be resolved before cmcrameri/matplotlib).

**Comment by srepmub** [comment]
implemented on the python side, by using the python 'cmcrameri' library (available in conda-forge). what's nice is that it returns matplotlib colormap objects :)

note that cmcrameri colormaps are also available via matplotlib itself as 'cmc.*', for example 'cmc.hawaii'. we only need to import cmcrameri for its colormaps to be registered with matplotlib under this namespace. but I guess it's nice if users can drop 'cmc.'.
