### ISSUE TITLE
Undocumented option 'datatype' for avl.MapPlot

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/atmosphere-virtual-lab#7]
This is mentioned in the documentation, but actually doesn't work:

```
plot = avl.MapPlot()
```
(`missing 1 required positional argument: 'data_type'`)

The data_type parameter is also missing in the function documentation of `avl.MapPlot()` itself.

I also don't understand why this parameter is needed for the plot itself. Shouldn't this be a parameter of the data trace?

**Comment by srepmub** [comment]
yes, this is a remnant from when we supported just a single trace per plot. I did have this as a TODO, but yeah.. :package: 

fixed now.

note: when I add multiple traces, I only see 'layer 1' in the map plot.. @martti that seems incorrect..?

**Comment by srepmub** [comment]
layers seem to work for martti. looks like I'm just on an old version of the js code.
